output-folder: gdrive://10QHbqyvptmZX4yhu2Y38YJbVHqINRr0n
max-days: 7
projects:
  - sdv
  - ctgan
  - copulas
  - rdt
  - deepecho
  - sdmetrics
  - sdgym
  - gretel-synthetics
  - ydata-synthetic
  - synthesized
  - datomize
  - gretel-trainer
  - ydata-sdk
  - mostlyai
  - synthcity
  - smartnoise-synth
  - realtabformer
  - be-great
