max-days: 7
projects:
  - sdv
  - ctgan
  - copulas
  - rdt
  - deepecho
  - sdmetrics
  - sdgym
  - synthesized
  - datomize
  - synthcity
  - smartnoise-synth
  - realtabformer
  - be-great
  - ydata-synthetic
  - ydata-sdk
  - gretel-synthetics
  - gretel-trainer
  - gretel-client
  - mostlyai
  - mostlyai-mock
