output-folder: gdrive://10QHbqyvptmZX4yhu2Y38YJbVHqINRr0n
projects:
  - ecosystem_name: "sdv"
    base_project: "sdv"
    dependency_projects: ["rdt", "copulas", "ctgan", "deepecho", "sdmetrics"]
    extra_projects: ["sdgym"]
    calculate_breakdown: true
  - ecosystem_name: "Gretel"
    projects: ["gretel-synthetics", "gretel-trainer"]
  - ecosystem_name: "be-great"
    projects: ["be-great"]
  - ecosystem_name: "realtabformer"
    projects: ["realtabformer"]
  - ecosystem_name: "smartnoise-synth"
    projects: ["smartnoise-synth"]
  - ecosystem_name: "synthcity"
    projects: ["synthcity"]

vendors:
  - ecosystem_name: "Vendor 1"
    name: "Synthesized"
    projects: ["synthesized"]
  - ecosystem_name: "Vendor 2"
    name: "ydata"
    projects: ["ydata-synthetic", "ydata-sdk"]
  - ecosystem_name: "Vendor 3"
    name: "datomize"
    projects: ["datomize"]
  - ecosystem_name: "Vendor 4"
    name: "mostlyai"
    projects: ["mostlyai", "mostlyai-mock"]
