output-folder: gdrive://10QHbqyvptmZX4yhu2Y38YJbVHqINRr0n
projects:
  - name: "sdv"
    base_project: "sdv"
    dependency_projects: ["rdt", "copulas", "ctgan", "deepecho", "sdmetrics"]
    extra_projects: ["sdgym"]
  - name: "Gretel"
    projects: ["gretel-synthetics", "gretel-trainer"]
  - name: "be-great"
    projects: ["be-great"]
  - name: "realtabformer"
    projects: ["realtabformer"]
  - name: "smartnoise-synth"
    projects: ["smartnoise-synth"]
  - name: "synthcity"
    projects: ["synthcity"]

vendors:
  - number: 1
    name: "Synthesized"
    projects: ["synthesized"]
  - number: 2
    name: "ydata"
    projects: ["ydata-synthetic", "ydata-sdk"]
  - number: 3
    name: "datomize"
    projects: ["datomize"]
  - number: 4
    name: "mostlyai"
    projects: ["mostlyai", "mostlyai-mock"]
