name: Daily Summarize

on:
  workflow_dispatch:
    inputs:
      slack_channel:
        description: Slack channel to post the error message to if the summarize job fail.
        required: false
        default: "sdv-alerts-debug"
  schedule:
    - cron:  '0 0 * * *'

jobs:
  summarize:
    runs-on: ubuntu-latest-large
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - name: Set up latest Python
      uses: actions/setup-python@v5
      with:
        python-version-file: 'pyproject.toml'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
    - name: Summarize Data from pypi.csv
      run: |
        download-analytics summarize \
          --output-folder gdrive://10QHbqyvptmZX4yhu2Y38YJbVHqINRr0n
      env:
        PYDRIVE_CREDENTIALS: ${{ secrets.PYDRIVE_CREDENTIALS }}

  alert:
    needs: [collect]
    runs-on: ubuntu-latest
    if: failure()
    steps:
    - uses: actions/checkout@v4
    - name: Set up latest Python
      uses: actions/setup-python@v5
      with:
        python-version-file: 'pyproject.toml'
    - name: Install slack dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install invoke
        python -m pip install .[dev]
    - name: Slack alert if failure
      run: python -m download_analytics.slack_utils -r ${{ github.run_id }} -c ${{ github.event.inputs.slack_channel || 'sdv-alerts' }}
      env:
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
