name: Daily Collection

on:
  workflow_dispatch:
    inputs:
      slack_channel:
        description: Slack channel to post the error message to if the builds fail.
        required: false
        default: "sdv-alerts-debug"
  schedule:
    - cron:  '0 0 * * *'

jobs:
  collect:
    runs-on: ubuntu-latest-large
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        activate-environment: true
    - name: Install pip and dependencies
      run: |
        uv pip install -U pip
        uv pip install -e .
    - name: Collect Downloads Data
      run: |
        uv run download-analytics collect
          --verbose \
          --max-days 30 \
          --add-metrics \
          --output-folder gdrive://***REMOVED***
      env:
        PYDRIVE_CREDENTIALS: ${{ secrets.PYDRIVE_CREDENTIALS }}
        BIGQUERY_CREDENTIALS: ${{ secrets.BIGQUERY_CREDENTIALS }}

  alert:
    needs: [collect]
    runs-on: ubuntu-latest
    if: failure()
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        activate-environment: true
    - name: Install pip and dependencies
      run: |
        uv pip install -U pip
        uv pip install -e .[dev]
    - name: Slack alert if failure
      run: uv run python -m download_analytics.slack_utils -r ${{ github.run_id }} -c ${{ github.event.inputs.slack_channel || 'sdv-alerts' }}
      env:
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
