name: Daily Summarize

on:
  workflow_dispatch:
    inputs:
      slack_channel:
        description: Slack channel to post the error message to if the summarize job fail.
        required: false
        default: "sdv-alerts-debug"
  schedule:
    - cron:  '0 1 * * *'

jobs:
  summarize:
    runs-on: ubuntu-latest-large
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        activate-environment: true
        python-version: "3.13"
    - name: Install dependencies and run summarize
      run: |
        uv pip install -U pip
        uv pip install -e .
        uv run download-analytics summarize \
          --output-folder gdrive://10QHbqyvptmZX4yhu2Y38YJbVHqINRr0n
      env:
        PYDRIVE_CREDENTIALS: ${{ secrets.PYDRIVE_CREDENTIALS }}
    - uses: actions/checkout@v4
      with:
        repository: sdv-dev/sdv-dev.github.io
        path: sdv-dev.github.io
        ref: 'gatsby-home'
        token: ${{ secrets.GITHUB_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    - name: Write to sdv-dev.github.io repo
      run: |
        ls
        find ./ -name '*.xlsx' -exec cp -prv '{}' 'sdv-dev.github.io/assets/' ';'
        cd sdv-dev.github.io
        git config --local user.name "github-actions[bot]"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add --force assets/*.xlsx
        git commit -m "Upload Download Summary"
        git remote set-url origin https://sdv-team:${{ secrets.GITHUB_TOKEN }}@github.com/sdv-dev/sdv-dev.github.io
        git push origin gatsby-home
      env:
        GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
  # alert:
  #   needs: [summarize]
  #   runs-on: ubuntu-latest
  #   if: failure()
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Set up latest Python
  #     uses: actions/setup-python@v5
  #     with:
  #       python-version-file: 'pyproject.toml'
  #   - name: Install slack dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       python -m pip install invoke
  #       python -m pip install .[dev]
  #   - name: Slack alert if failure
  #     run: |
  #       python -m download_analytics.slack_utils \
  #       -r ${{ github.run_id }} \
  #       -c ${{ github.event.inputs.slack_channel || 'sdv-alerts' }} \
  #       -m 'Summarize Analytics build failed :fire: :dumpster-fire: :fire:'
  #     env:
  #       SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
