name: Dry Run Collect and Summarize
on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  dry_run:
    environment: stage
    runs-on: ubuntu-latest-large
    timeout-minutes: 25
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        activate-environment: true
        cache-dependency-glob: |
          **/pyproject.toml
          **/__main__.py
    - name: Install pip and dependencies
      run: |
        uv pip install .
    - name: Collect PyPI Downloads - Dry Run
      run: |
        uv run pymetrics collect-pypi \
          --max-days 30 \
          --add-metrics \
          --output-folder ${{ secrets.PYPI_OUTPUT_FOLDER }} \
          --dry-run
      env:
        PYDRIVE_CREDENTIALS: ${{ secrets.PYDRIVE_CREDENTIALS }}
        BIGQUERY_CREDENTIALS: ${{ secrets.BIGQUERY_CREDENTIALS }}
        PYPI_OUTPUT_FOLDER: ${{ secrets.PYPI_OUTPUT_FOLDER }}
    - name: Collect Anaconda Downloads - Dry Run
      run: |
        uv run pymetrics collect-anaconda \
          --max-days 90 \
          --output-folder ${{ secrets.ANACONDA_OUTPUT_FOLDER }} \
          --dry-run
      env:
        PYDRIVE_CREDENTIALS: ${{ secrets.PYDRIVE_CREDENTIALS }}
        ANACONDA_OUTPUT_FOLDER: ${{ secrets.ANACONDA_OUTPUT_FOLDER }}
    - name: Summarize - Dry Run
      run: |
        uv run pymetrics summarize \
          --input-folder ${{ secrets.PYPI_OUTPUT_FOLDER }} \
          --dry-run
      env:
        PYDRIVE_CREDENTIALS: ${{ secrets.PYDRIVE_CREDENTIALS }}
        PYPI_OUTPUT_FOLDER: ${{ secrets.PYPI_OUTPUT_FOLDER }}
