name: Health-check Dry Run

on:
  - workflow_dispatch
  - push
  - pull_request

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
    - name: Collect Downloads Data
      run: |
        download-analytics collect \
          --verbose \
          --max-days 30 \
          --add-metrics \
          --output-folder gdrive://***REMOVED*** \
          --dry-run
      env:
        PYDRIVE_CREDENTIALS: ${{ secrets.PYDRIVE_CREDENTIALS }}
        BIGQUERY_CREDENTIALS: ${{ secrets.BIGQUERY_CREDENTIALS }}
