name: Dry Run Collect and Summarize
on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  dry_run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
    - name: Collect Downloads Data - Dry Run
      run: |
        download-analytics collect \
          --verbose \
          --max-days 30 \
          --add-metrics \
          --output-folder gdrive://10QHbqyvptmZX4yhu2Y38YJbVHqINRr0n \
          --dry-run
      env:
        PYDRIVE_CREDENTIALS: ${{ secrets.PYDRIVE_CREDENTIALS }}
        BIGQUERY_CREDENTIALS: ${{ secrets.BIGQUERY_CREDENTIALS }}
    - name: Run Summarize - Dry Run
      run: |
        uv run download-analytics summarize \
          --output-folder gdrive://10QHbqyvptmZX4yhu2Y38YJbVHqINRr0n \
          --dry-run
      env:
        PYDRIVE_CREDENTIALS: ${{ secrets.PYDRIVE_CREDENTIALS }}