name: Dry Run Collect and Summarize
on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  dry_run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        activate-environment: true
    - name: Install pip and dependencies
      run: |
        uv pip install -U pip
        uv pip install .
    - name: Collect PyPI Downloads - Dry Run
      run: |
        uv run download-analytics collect-pypi \
          --verbose \
          --max-days 30 \
          --add-metrics \
          --output-folder gdrive://10QHbqyvptmZX4yhu2Y38YJbVHqINRr0n \
          --dry-run
      env:
        PYDRIVE_CREDENTIALS: ${{ secrets.PYDRIVE_CREDENTIALS }}
        BIGQUERY_CREDENTIALS: ${{ secrets.BIGQUERY_CREDENTIALS }}
    - name: Collect Anaconda Downloads - Dry Run
      run: |
        uv run download-analytics collect-anaconda \
          --output-folder gdrive://1UnDYovLkL4gletOF5328BG1X59mSHF-Z \
          --max-days 90 \
          --verbose \
          --dry-run
      env:
        PYDRIVE_CREDENTIALS: ${{ secrets.PYDRIVE_CREDENTIALS }}
    - name: Summarize - Dry Run
      run: |
        uv run download-analytics summarize \
          --verbose \
          --output-folder gdrive://10QHbqyvptmZX4yhu2Y38YJbVHqINRr0n \
          --dry-run
      env:
        PYDRIVE_CREDENTIALS: ${{ secrets.PYDRIVE_CREDENTIALS }}