name: Health-check Dry Run
on:
  workflow_dispatch:
    inputs:
      slack_channel:
        description: Slack channel to post the error message to if the builds fail.
        required: false
        default: "sdv-alerts-debug"
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
jobs:
  dry_run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
    - name: Collect Downloads Data
      run: |
        download-analytics collect \
          --verbose \
          --max-days 30 \
          --add-metrics \
          --output-folder gdrive://10QHbqyvptmZX4yhu2Y38YJbVHqINRr0n \
          --dry-run
      env:
        PYDRIVE_CREDENTIALS: ${{ secrets.PYDRIVE_CREDENTIALS }}
        BIGQUERY_CREDENTIALS: ${{ secrets.BIGQUERY_CREDENTIALS }}

  alert:
    needs: [dry_run]
    runs-on: ubuntu-latest
    if: failure()
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install slack dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install invoke
        python -m pip install .[dev]
    - name: Slack alert if failure
      run: python -m download_analytics.slack_utils -r ${{ github.run_id }} -c ${{ github.event.inputs.slack_channel || 'sdv-alerts' }}
      env:
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
