name: Dry Run Collect and Summarize
on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  dry_run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        activate-environment: true
    - name: Install pip and dependencies
      run: |
        uv pip install -U pip
        uv pip install .
    - name: Collect Downloads Data - Dry Run
      run: |
        uv run download-analytics collect \
          --verbose \
          --max-days 30 \
          --add-metrics \
          --output-folder gdrive://***REMOVED*** \
          --dry-run
      env:
        PYDRIVE_CREDENTIALS: ${{ secrets.PYDRIVE_CREDENTIALS }}
        BIGQUERY_CREDENTIALS: ${{ secrets.BIGQUERY_CREDENTIALS }}
    - name: Run Summarize - Dry Run
      run: |
        uv run download-analytics summarize \
          --verbose \
          --output-folder gdrive://***REMOVED*** \
          --dry-run
      env:
        PYDRIVE_CREDENTIALS: ${{ secrets.PYDRIVE_CREDENTIALS }}
