name: Manual Collection

on:
  workflow_dispatch:
    inputs:
      projects:
        description: 'List of projects or libraries to collect, separated by spaces (e.g. sdv rdt)'
        required: false
        default: ''
      output_folder:
        description: 'ID of the Google Drive Output folder'
        required: false
        default: '10QHbqyvptmZX4yhu2Y38YJbVHqINRr0n'
      max_days:
        description: 'Maximum number of days to collect, starting from today.'
        required: false
        default: '7'
      extras:
        description: 'Extra arguments to pass (e.g. --dry-run --force --start-date --add-metrics)'
        required: false
        default: '--add-metrics'

jobs:
  collect:
    runs-on: ubuntu-latest-large
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
    - name: Collect Downloads Data
      run: |
        download-analytics collect \
          --verbose \
          --projects ${{ github.event.inputs.projects }} \
          ${{ github.event.inputs.max_days && '--max-days ' || '' }} \
          ${{ github.event.inputs.max_days && github.event.inputs.max_days || '' }} \
          --output-folder gdrive://${{ github.event.inputs.output_folder }} \
          ${{ github.event.inputs.extras }}
      env:
        PYDRIVE_CREDENTIALS: ${{ secrets.PYDRIVE_CREDENTIALS }}
        BIGQUERY_CREDENTIALS: ${{ secrets.BIGQUERY_CREDENTIALS }}
